<?php

namespace ContainerHZHteH6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P_IC6ETService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p.IC6ET' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p.IC6ET'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.j4tB2XU', 'get_ServiceLocator_J4tB2XUService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.elP7wZ0', 'get_ServiceLocator_ElP7wZ0Service', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\ProfileController::addUser' => ['privates', '.service_locator.Qkluc2L', 'get_ServiceLocator_Qkluc2LService', true],
            'App\\Controller\\ProfileController::deleteProduct' => ['privates', '.service_locator.no630kw', 'get_ServiceLocator_No630kwService', true],
            'App\\Controller\\ProfileController::editUser' => ['privates', '.service_locator.e5mLIHW', 'get_ServiceLocator_E5mLIHWService', true],
            'App\\Controller\\ProfileController::userList' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.LfWppqE', 'get_ServiceLocator_LfWppqEService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.j4tB2XU', 'get_ServiceLocator_J4tB2XUService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.elP7wZ0', 'get_ServiceLocator_ElP7wZ0Service', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\ProfileController:addUser' => ['privates', '.service_locator.Qkluc2L', 'get_ServiceLocator_Qkluc2LService', true],
            'App\\Controller\\ProfileController:deleteProduct' => ['privates', '.service_locator.no630kw', 'get_ServiceLocator_No630kwService', true],
            'App\\Controller\\ProfileController:editUser' => ['privates', '.service_locator.e5mLIHW', 'get_ServiceLocator_E5mLIHWService', true],
            'App\\Controller\\ProfileController:userList' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.LfWppqE', 'get_ServiceLocator_LfWppqEService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProfileController::addUser' => '?',
            'App\\Controller\\ProfileController::deleteProduct' => '?',
            'App\\Controller\\ProfileController::editUser' => '?',
            'App\\Controller\\ProfileController::userList' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProfileController:addUser' => '?',
            'App\\Controller\\ProfileController:deleteProduct' => '?',
            'App\\Controller\\ProfileController:editUser' => '?',
            'App\\Controller\\ProfileController:userList' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
