<?php

namespace ContainerE6AZ3Qn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ET5jwaxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eT5jwax' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eT5jwax'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['privates', '.errored.rUMfXRG', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfileController::editUser()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'passwordEncoder' => ['privates', '.errored.hD2fI8K', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfileController::editUser()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.juq_B_n', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfileController::editUser()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'user' => ['privates', '.errored.NbpqU7H', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfileController::editUser()": the $user argument is type-hinted with the non-existent class or interface: "App\\Controller\\User". Did you forget to add a use statement?'],
        ], [
            'em' => '?',
            'passwordEncoder' => '?',
            'request' => '?',
            'user' => '?',
        ]);
    }
}
