<?php

namespace ContainerE6AZ3Qn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FDaPwGmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FDaPwGm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FDaPwGm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['privates', '.errored.4CpuRlC', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfileController::addUser()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
            'passwordEncoder' => ['privates', '.errored.ppC87I_', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfileController::addUser()": the $passwordEncoder argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordEncoderInterface". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.VXN8JdE', NULL, 'Cannot determine controller argument for "App\\Controller\\ProfileController::addUser()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
        ], [
            'em' => '?',
            'passwordEncoder' => '?',
            'request' => '?',
        ]);
    }
}
