<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHZHteH6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHZHteH6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHZHteH6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHZHteH6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHZHteH6\App_KernelDevDebugContainer([
    'container.build_hash' => 'HZHteH6',
    'container.build_id' => 'c58b4892',
    'container.build_time' => 1611234161,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHZHteH6');
